<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 15 Mar 2012 14:01:45 +0000
 */
$conf['title'] = 'ReMust';
$conf['lang'] = 'pl';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
